/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace AiCTFAdapter {
  export type MarketQuestionStruct = {
    resolutionTime: BigNumberish;
    proposedAt: BigNumberish;
    proposedPayouts: BigNumberish[];
    outcomeCount: BigNumberish;
    status: BigNumberish;
    multisigApproved: boolean;
  };

  export type MarketQuestionStructOutput = [
    resolutionTime: bigint,
    proposedAt: bigint,
    proposedPayouts: bigint[],
    outcomeCount: bigint,
    status: bigint,
    multisigApproved: boolean
  ] & {
    resolutionTime: bigint;
    proposedAt: bigint;
    proposedPayouts: bigint[];
    outcomeCount: bigint;
    status: bigint;
    multisigApproved: boolean;
  };
}

export interface AiCTFAdapterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "adminOverride"
      | "adminResolve"
      | "ctf"
      | "disputeWindow"
      | "finalizeResolution"
      | "getDisputeWindowEnd"
      | "getExpectedAuthor"
      | "getExpectedWorkflowId"
      | "getExpectedWorkflowName"
      | "getForwarderAddress"
      | "getMultisigSigners"
      | "getQuestion"
      | "initializeMarket"
      | "isMultisigSigner"
      | "multisigApprovalCount"
      | "multisigApprovals"
      | "multisigOverride"
      | "multisigSigners"
      | "multisigThreshold"
      | "onReport"
      | "owner"
      | "questions"
      | "registry"
      | "renounceOwnership"
      | "setDisputeWindow"
      | "setExpectedAuthor"
      | "setExpectedWorkflowId"
      | "setExpectedWorkflowName"
      | "setForwarderAddress"
      | "setMultisigSigners"
      | "setRegistry"
      | "setUpkeepFinalizer"
      | "supportsInterface"
      | "transferOwnership"
      | "upkeepFinalizer"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DisputeWindowUpdated"
      | "ExpectedAuthorUpdated"
      | "ExpectedWorkflowIdUpdated"
      | "ExpectedWorkflowNameUpdated"
      | "ForwarderAddressUpdated"
      | "MarketInitialized"
      | "MarketResolved"
      | "MultisigOverrideApproved"
      | "MultisigSignersUpdated"
      | "MultisigThresholdUpdated"
      | "OwnershipTransferred"
      | "RegistryUpdated"
      | "ResolutionProposalReplaced"
      | "ResolutionProposed"
      | "SecurityWarning"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "adminOverride",
    values: [BytesLike, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "adminResolve",
    values: [BytesLike, BigNumberish[]]
  ): string;
  encodeFunctionData(functionFragment: "ctf", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "disputeWindow",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeResolution",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDisputeWindowEnd",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getExpectedAuthor",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getExpectedWorkflowId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getExpectedWorkflowName",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getForwarderAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMultisigSigners",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getQuestion",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initializeMarket",
    values: [BytesLike, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isMultisigSigner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "multisigApprovalCount",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "multisigApprovals",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "multisigOverride",
    values: [BytesLike, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "multisigSigners",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "multisigThreshold",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "onReport",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "questions",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "registry", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setDisputeWindow",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setExpectedAuthor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setExpectedWorkflowId",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setExpectedWorkflowName",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setForwarderAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setMultisigSigners",
    values: [AddressLike[], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setRegistry",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setUpkeepFinalizer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "upkeepFinalizer",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "adminOverride",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "adminResolve",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ctf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "disputeWindow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizeResolution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDisputeWindowEnd",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getExpectedAuthor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getExpectedWorkflowId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getExpectedWorkflowName",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getForwarderAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMultisigSigners",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getQuestion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initializeMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isMultisigSigner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "multisigApprovalCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "multisigApprovals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "multisigOverride",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "multisigSigners",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "multisigThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "onReport", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "questions", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "registry", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDisputeWindow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setExpectedAuthor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setExpectedWorkflowId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setExpectedWorkflowName",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setForwarderAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMultisigSigners",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setUpkeepFinalizer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upkeepFinalizer",
    data: BytesLike
  ): Result;
}

export namespace DisputeWindowUpdatedEvent {
  export type InputTuple = [newWindow: BigNumberish];
  export type OutputTuple = [newWindow: bigint];
  export interface OutputObject {
    newWindow: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExpectedAuthorUpdatedEvent {
  export type InputTuple = [
    previousAuthor: AddressLike,
    newAuthor: AddressLike
  ];
  export type OutputTuple = [previousAuthor: string, newAuthor: string];
  export interface OutputObject {
    previousAuthor: string;
    newAuthor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExpectedWorkflowIdUpdatedEvent {
  export type InputTuple = [previousId: BytesLike, newId: BytesLike];
  export type OutputTuple = [previousId: string, newId: string];
  export interface OutputObject {
    previousId: string;
    newId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExpectedWorkflowNameUpdatedEvent {
  export type InputTuple = [previousName: BytesLike, newName: BytesLike];
  export type OutputTuple = [previousName: string, newName: string];
  export interface OutputObject {
    previousName: string;
    newName: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ForwarderAddressUpdatedEvent {
  export type InputTuple = [
    previousForwarder: AddressLike,
    newForwarder: AddressLike
  ];
  export type OutputTuple = [previousForwarder: string, newForwarder: string];
  export interface OutputObject {
    previousForwarder: string;
    newForwarder: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketInitializedEvent {
  export type InputTuple = [
    questionId: BytesLike,
    ipfsCid: string,
    outcomeCount: BigNumberish,
    resolutionTime: BigNumberish
  ];
  export type OutputTuple = [
    questionId: string,
    ipfsCid: string,
    outcomeCount: bigint,
    resolutionTime: bigint
  ];
  export interface OutputObject {
    questionId: string;
    ipfsCid: string;
    outcomeCount: bigint;
    resolutionTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketResolvedEvent {
  export type InputTuple = [questionId: BytesLike, payouts: BigNumberish[]];
  export type OutputTuple = [questionId: string, payouts: bigint[]];
  export interface OutputObject {
    questionId: string;
    payouts: bigint[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MultisigOverrideApprovedEvent {
  export type InputTuple = [
    questionId: BytesLike,
    signer: AddressLike,
    approvalsNow: BigNumberish,
    threshold: BigNumberish
  ];
  export type OutputTuple = [
    questionId: string,
    signer: string,
    approvalsNow: bigint,
    threshold: bigint
  ];
  export interface OutputObject {
    questionId: string;
    signer: string;
    approvalsNow: bigint;
    threshold: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MultisigSignersUpdatedEvent {
  export type InputTuple = [newSigners: AddressLike[]];
  export type OutputTuple = [newSigners: string[]];
  export interface OutputObject {
    newSigners: string[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MultisigThresholdUpdatedEvent {
  export type InputTuple = [newThreshold: BigNumberish];
  export type OutputTuple = [newThreshold: bigint];
  export interface OutputObject {
    newThreshold: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RegistryUpdatedEvent {
  export type InputTuple = [newRegistry: AddressLike];
  export type OutputTuple = [newRegistry: string];
  export interface OutputObject {
    newRegistry: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ResolutionProposalReplacedEvent {
  export type InputTuple = [
    questionId: BytesLike,
    newPayouts: BigNumberish[],
    replacedBy: AddressLike
  ];
  export type OutputTuple = [
    questionId: string,
    newPayouts: bigint[],
    replacedBy: string
  ];
  export interface OutputObject {
    questionId: string;
    newPayouts: bigint[];
    replacedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ResolutionProposedEvent {
  export type InputTuple = [
    questionId: BytesLike,
    payouts: BigNumberish[],
    disputeWindowEnd: BigNumberish
  ];
  export type OutputTuple = [
    questionId: string,
    payouts: bigint[],
    disputeWindowEnd: bigint
  ];
  export interface OutputObject {
    questionId: string;
    payouts: bigint[];
    disputeWindowEnd: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SecurityWarningEvent {
  export type InputTuple = [message: string];
  export type OutputTuple = [message: string];
  export interface OutputObject {
    message: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AiCTFAdapter extends BaseContract {
  connect(runner?: ContractRunner | null): AiCTFAdapter;
  waitForDeployment(): Promise<this>;

  interface: AiCTFAdapterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  adminOverride: TypedContractMethod<
    [questionId: BytesLike, payouts: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  adminResolve: TypedContractMethod<
    [questionId: BytesLike, payouts: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  ctf: TypedContractMethod<[], [string], "view">;

  disputeWindow: TypedContractMethod<[], [bigint], "view">;

  finalizeResolution: TypedContractMethod<
    [questionId: BytesLike],
    [void],
    "nonpayable"
  >;

  getDisputeWindowEnd: TypedContractMethod<
    [questionId: BytesLike],
    [bigint],
    "view"
  >;

  getExpectedAuthor: TypedContractMethod<[], [string], "view">;

  getExpectedWorkflowId: TypedContractMethod<[], [string], "view">;

  getExpectedWorkflowName: TypedContractMethod<[], [string], "view">;

  getForwarderAddress: TypedContractMethod<[], [string], "view">;

  getMultisigSigners: TypedContractMethod<[], [string[]], "view">;

  getQuestion: TypedContractMethod<
    [questionId: BytesLike],
    [AiCTFAdapter.MarketQuestionStructOutput],
    "view"
  >;

  initializeMarket: TypedContractMethod<
    [
      questionId: BytesLike,
      ipfsCid: string,
      outcomeCount: BigNumberish,
      resolutionTime: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  isMultisigSigner: TypedContractMethod<[addr: AddressLike], [boolean], "view">;

  multisigApprovalCount: TypedContractMethod<
    [arg0: BytesLike],
    [bigint],
    "view"
  >;

  multisigApprovals: TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [boolean],
    "view"
  >;

  multisigOverride: TypedContractMethod<
    [questionId: BytesLike, payouts: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  multisigSigners: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  multisigThreshold: TypedContractMethod<[], [bigint], "view">;

  onReport: TypedContractMethod<
    [metadata: BytesLike, report: BytesLike],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  questions: TypedContractMethod<
    [arg0: BytesLike],
    [
      [bigint, bigint, bigint, bigint, boolean] & {
        resolutionTime: bigint;
        proposedAt: bigint;
        outcomeCount: bigint;
        status: bigint;
        multisigApproved: boolean;
      }
    ],
    "view"
  >;

  registry: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setDisputeWindow: TypedContractMethod<
    [_window: BigNumberish],
    [void],
    "nonpayable"
  >;

  setExpectedAuthor: TypedContractMethod<
    [_author: AddressLike],
    [void],
    "nonpayable"
  >;

  setExpectedWorkflowId: TypedContractMethod<
    [_id: BytesLike],
    [void],
    "nonpayable"
  >;

  setExpectedWorkflowName: TypedContractMethod<
    [_name: string],
    [void],
    "nonpayable"
  >;

  setForwarderAddress: TypedContractMethod<
    [_forwarder: AddressLike],
    [void],
    "nonpayable"
  >;

  setMultisigSigners: TypedContractMethod<
    [_signers: AddressLike[], _threshold: BigNumberish],
    [void],
    "nonpayable"
  >;

  setRegistry: TypedContractMethod<
    [_registry: AddressLike],
    [void],
    "nonpayable"
  >;

  setUpkeepFinalizer: TypedContractMethod<
    [_finalizer: AddressLike],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  upkeepFinalizer: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "adminOverride"
  ): TypedContractMethod<
    [questionId: BytesLike, payouts: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "adminResolve"
  ): TypedContractMethod<
    [questionId: BytesLike, payouts: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "ctf"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "disputeWindow"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "finalizeResolution"
  ): TypedContractMethod<[questionId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getDisputeWindowEnd"
  ): TypedContractMethod<[questionId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getExpectedAuthor"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getExpectedWorkflowId"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getExpectedWorkflowName"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getForwarderAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getMultisigSigners"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getQuestion"
  ): TypedContractMethod<
    [questionId: BytesLike],
    [AiCTFAdapter.MarketQuestionStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "initializeMarket"
  ): TypedContractMethod<
    [
      questionId: BytesLike,
      ipfsCid: string,
      outcomeCount: BigNumberish,
      resolutionTime: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isMultisigSigner"
  ): TypedContractMethod<[addr: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "multisigApprovalCount"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "multisigApprovals"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "multisigOverride"
  ): TypedContractMethod<
    [questionId: BytesLike, payouts: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "multisigSigners"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "multisigThreshold"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "onReport"
  ): TypedContractMethod<
    [metadata: BytesLike, report: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "questions"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [bigint, bigint, bigint, bigint, boolean] & {
        resolutionTime: bigint;
        proposedAt: bigint;
        outcomeCount: bigint;
        status: bigint;
        multisigApproved: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "registry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setDisputeWindow"
  ): TypedContractMethod<[_window: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setExpectedAuthor"
  ): TypedContractMethod<[_author: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setExpectedWorkflowId"
  ): TypedContractMethod<[_id: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setExpectedWorkflowName"
  ): TypedContractMethod<[_name: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setForwarderAddress"
  ): TypedContractMethod<[_forwarder: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMultisigSigners"
  ): TypedContractMethod<
    [_signers: AddressLike[], _threshold: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setRegistry"
  ): TypedContractMethod<[_registry: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setUpkeepFinalizer"
  ): TypedContractMethod<[_finalizer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "upkeepFinalizer"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "DisputeWindowUpdated"
  ): TypedContractEvent<
    DisputeWindowUpdatedEvent.InputTuple,
    DisputeWindowUpdatedEvent.OutputTuple,
    DisputeWindowUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ExpectedAuthorUpdated"
  ): TypedContractEvent<
    ExpectedAuthorUpdatedEvent.InputTuple,
    ExpectedAuthorUpdatedEvent.OutputTuple,
    ExpectedAuthorUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ExpectedWorkflowIdUpdated"
  ): TypedContractEvent<
    ExpectedWorkflowIdUpdatedEvent.InputTuple,
    ExpectedWorkflowIdUpdatedEvent.OutputTuple,
    ExpectedWorkflowIdUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ExpectedWorkflowNameUpdated"
  ): TypedContractEvent<
    ExpectedWorkflowNameUpdatedEvent.InputTuple,
    ExpectedWorkflowNameUpdatedEvent.OutputTuple,
    ExpectedWorkflowNameUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ForwarderAddressUpdated"
  ): TypedContractEvent<
    ForwarderAddressUpdatedEvent.InputTuple,
    ForwarderAddressUpdatedEvent.OutputTuple,
    ForwarderAddressUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "MarketInitialized"
  ): TypedContractEvent<
    MarketInitializedEvent.InputTuple,
    MarketInitializedEvent.OutputTuple,
    MarketInitializedEvent.OutputObject
  >;
  getEvent(
    key: "MarketResolved"
  ): TypedContractEvent<
    MarketResolvedEvent.InputTuple,
    MarketResolvedEvent.OutputTuple,
    MarketResolvedEvent.OutputObject
  >;
  getEvent(
    key: "MultisigOverrideApproved"
  ): TypedContractEvent<
    MultisigOverrideApprovedEvent.InputTuple,
    MultisigOverrideApprovedEvent.OutputTuple,
    MultisigOverrideApprovedEvent.OutputObject
  >;
  getEvent(
    key: "MultisigSignersUpdated"
  ): TypedContractEvent<
    MultisigSignersUpdatedEvent.InputTuple,
    MultisigSignersUpdatedEvent.OutputTuple,
    MultisigSignersUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "MultisigThresholdUpdated"
  ): TypedContractEvent<
    MultisigThresholdUpdatedEvent.InputTuple,
    MultisigThresholdUpdatedEvent.OutputTuple,
    MultisigThresholdUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RegistryUpdated"
  ): TypedContractEvent<
    RegistryUpdatedEvent.InputTuple,
    RegistryUpdatedEvent.OutputTuple,
    RegistryUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ResolutionProposalReplaced"
  ): TypedContractEvent<
    ResolutionProposalReplacedEvent.InputTuple,
    ResolutionProposalReplacedEvent.OutputTuple,
    ResolutionProposalReplacedEvent.OutputObject
  >;
  getEvent(
    key: "ResolutionProposed"
  ): TypedContractEvent<
    ResolutionProposedEvent.InputTuple,
    ResolutionProposedEvent.OutputTuple,
    ResolutionProposedEvent.OutputObject
  >;
  getEvent(
    key: "SecurityWarning"
  ): TypedContractEvent<
    SecurityWarningEvent.InputTuple,
    SecurityWarningEvent.OutputTuple,
    SecurityWarningEvent.OutputObject
  >;

  filters: {
    "DisputeWindowUpdated(uint256)": TypedContractEvent<
      DisputeWindowUpdatedEvent.InputTuple,
      DisputeWindowUpdatedEvent.OutputTuple,
      DisputeWindowUpdatedEvent.OutputObject
    >;
    DisputeWindowUpdated: TypedContractEvent<
      DisputeWindowUpdatedEvent.InputTuple,
      DisputeWindowUpdatedEvent.OutputTuple,
      DisputeWindowUpdatedEvent.OutputObject
    >;

    "ExpectedAuthorUpdated(address,address)": TypedContractEvent<
      ExpectedAuthorUpdatedEvent.InputTuple,
      ExpectedAuthorUpdatedEvent.OutputTuple,
      ExpectedAuthorUpdatedEvent.OutputObject
    >;
    ExpectedAuthorUpdated: TypedContractEvent<
      ExpectedAuthorUpdatedEvent.InputTuple,
      ExpectedAuthorUpdatedEvent.OutputTuple,
      ExpectedAuthorUpdatedEvent.OutputObject
    >;

    "ExpectedWorkflowIdUpdated(bytes32,bytes32)": TypedContractEvent<
      ExpectedWorkflowIdUpdatedEvent.InputTuple,
      ExpectedWorkflowIdUpdatedEvent.OutputTuple,
      ExpectedWorkflowIdUpdatedEvent.OutputObject
    >;
    ExpectedWorkflowIdUpdated: TypedContractEvent<
      ExpectedWorkflowIdUpdatedEvent.InputTuple,
      ExpectedWorkflowIdUpdatedEvent.OutputTuple,
      ExpectedWorkflowIdUpdatedEvent.OutputObject
    >;

    "ExpectedWorkflowNameUpdated(bytes10,bytes10)": TypedContractEvent<
      ExpectedWorkflowNameUpdatedEvent.InputTuple,
      ExpectedWorkflowNameUpdatedEvent.OutputTuple,
      ExpectedWorkflowNameUpdatedEvent.OutputObject
    >;
    ExpectedWorkflowNameUpdated: TypedContractEvent<
      ExpectedWorkflowNameUpdatedEvent.InputTuple,
      ExpectedWorkflowNameUpdatedEvent.OutputTuple,
      ExpectedWorkflowNameUpdatedEvent.OutputObject
    >;

    "ForwarderAddressUpdated(address,address)": TypedContractEvent<
      ForwarderAddressUpdatedEvent.InputTuple,
      ForwarderAddressUpdatedEvent.OutputTuple,
      ForwarderAddressUpdatedEvent.OutputObject
    >;
    ForwarderAddressUpdated: TypedContractEvent<
      ForwarderAddressUpdatedEvent.InputTuple,
      ForwarderAddressUpdatedEvent.OutputTuple,
      ForwarderAddressUpdatedEvent.OutputObject
    >;

    "MarketInitialized(bytes32,string,uint256,uint256)": TypedContractEvent<
      MarketInitializedEvent.InputTuple,
      MarketInitializedEvent.OutputTuple,
      MarketInitializedEvent.OutputObject
    >;
    MarketInitialized: TypedContractEvent<
      MarketInitializedEvent.InputTuple,
      MarketInitializedEvent.OutputTuple,
      MarketInitializedEvent.OutputObject
    >;

    "MarketResolved(bytes32,uint256[])": TypedContractEvent<
      MarketResolvedEvent.InputTuple,
      MarketResolvedEvent.OutputTuple,
      MarketResolvedEvent.OutputObject
    >;
    MarketResolved: TypedContractEvent<
      MarketResolvedEvent.InputTuple,
      MarketResolvedEvent.OutputTuple,
      MarketResolvedEvent.OutputObject
    >;

    "MultisigOverrideApproved(bytes32,address,uint256,uint256)": TypedContractEvent<
      MultisigOverrideApprovedEvent.InputTuple,
      MultisigOverrideApprovedEvent.OutputTuple,
      MultisigOverrideApprovedEvent.OutputObject
    >;
    MultisigOverrideApproved: TypedContractEvent<
      MultisigOverrideApprovedEvent.InputTuple,
      MultisigOverrideApprovedEvent.OutputTuple,
      MultisigOverrideApprovedEvent.OutputObject
    >;

    "MultisigSignersUpdated(address[])": TypedContractEvent<
      MultisigSignersUpdatedEvent.InputTuple,
      MultisigSignersUpdatedEvent.OutputTuple,
      MultisigSignersUpdatedEvent.OutputObject
    >;
    MultisigSignersUpdated: TypedContractEvent<
      MultisigSignersUpdatedEvent.InputTuple,
      MultisigSignersUpdatedEvent.OutputTuple,
      MultisigSignersUpdatedEvent.OutputObject
    >;

    "MultisigThresholdUpdated(uint256)": TypedContractEvent<
      MultisigThresholdUpdatedEvent.InputTuple,
      MultisigThresholdUpdatedEvent.OutputTuple,
      MultisigThresholdUpdatedEvent.OutputObject
    >;
    MultisigThresholdUpdated: TypedContractEvent<
      MultisigThresholdUpdatedEvent.InputTuple,
      MultisigThresholdUpdatedEvent.OutputTuple,
      MultisigThresholdUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RegistryUpdated(address)": TypedContractEvent<
      RegistryUpdatedEvent.InputTuple,
      RegistryUpdatedEvent.OutputTuple,
      RegistryUpdatedEvent.OutputObject
    >;
    RegistryUpdated: TypedContractEvent<
      RegistryUpdatedEvent.InputTuple,
      RegistryUpdatedEvent.OutputTuple,
      RegistryUpdatedEvent.OutputObject
    >;

    "ResolutionProposalReplaced(bytes32,uint256[],address)": TypedContractEvent<
      ResolutionProposalReplacedEvent.InputTuple,
      ResolutionProposalReplacedEvent.OutputTuple,
      ResolutionProposalReplacedEvent.OutputObject
    >;
    ResolutionProposalReplaced: TypedContractEvent<
      ResolutionProposalReplacedEvent.InputTuple,
      ResolutionProposalReplacedEvent.OutputTuple,
      ResolutionProposalReplacedEvent.OutputObject
    >;

    "ResolutionProposed(bytes32,uint256[],uint256)": TypedContractEvent<
      ResolutionProposedEvent.InputTuple,
      ResolutionProposedEvent.OutputTuple,
      ResolutionProposedEvent.OutputObject
    >;
    ResolutionProposed: TypedContractEvent<
      ResolutionProposedEvent.InputTuple,
      ResolutionProposedEvent.OutputTuple,
      ResolutionProposedEvent.OutputObject
    >;

    "SecurityWarning(string)": TypedContractEvent<
      SecurityWarningEvent.InputTuple,
      SecurityWarningEvent.OutputTuple,
      SecurityWarningEvent.OutputObject
    >;
    SecurityWarning: TypedContractEvent<
      SecurityWarningEvent.InputTuple,
      SecurityWarningEvent.OutputTuple,
      SecurityWarningEvent.OutputObject
    >;
  };
}
