/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as receiverTemplateSol from "./ReceiverTemplate.sol";
export type { receiverTemplateSol };
export type { AiCTFAdapter } from "./AiCTFAdapter";
export type { AutoFinalizerUpkeep } from "./AutoFinalizerUpkeep";
export type { ConditionalTokens } from "./ConditionalTokens";
export type { MarketRegistry } from "./MarketRegistry";
export type { MockEURC } from "./MockEURC";
export type { MockUSDC } from "./MockUSDC";
export type { PredictionMarket } from "./PredictionMarket";
export type { PredictionMarketAMM } from "./PredictionMarketAMM";
export type { PredictionMarketToken } from "./PredictionMarketToken";
