/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace MarketRegistry {
  export type MarketInfoStruct = {
    outcomeCount: BigNumberish;
    resolutionTime: BigNumberish;
    status: BigNumberish;
    exists: boolean;
  };

  export type MarketInfoStructOutput = [
    outcomeCount: bigint,
    resolutionTime: bigint,
    status: bigint,
    exists: boolean
  ] & {
    outcomeCount: bigint;
    resolutionTime: bigint;
    status: bigint;
    exists: boolean;
  };
}

export interface MarketRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "adapter"
      | "allMarkets"
      | "createMarket"
      | "getAllMarkets"
      | "getMarket"
      | "getMarketCount"
      | "getMarketsPage"
      | "marketSettlementRail"
      | "markets"
      | "owner"
      | "renounceOwnership"
      | "syncStatus"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "MarketCreated"
      | "MarketStatusUpdated"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(functionFragment: "adapter", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "allMarkets",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createMarket",
    values: [string, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllMarkets",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMarket",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMarketCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMarketsPage",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "marketSettlementRail",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "markets", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "syncStatus",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "adapter", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "allMarkets", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllMarkets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getMarket", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getMarketCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMarketsPage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "marketSettlementRail",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "markets", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "syncStatus", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace MarketCreatedEvent {
  export type InputTuple = [
    questionId: BytesLike,
    ipfsCid: string,
    outcomeCount: BigNumberish,
    resolutionTime: BigNumberish,
    creator: AddressLike,
    settlementRail: BigNumberish
  ];
  export type OutputTuple = [
    questionId: string,
    ipfsCid: string,
    outcomeCount: bigint,
    resolutionTime: bigint,
    creator: string,
    settlementRail: bigint
  ];
  export interface OutputObject {
    questionId: string;
    ipfsCid: string;
    outcomeCount: bigint;
    resolutionTime: bigint;
    creator: string;
    settlementRail: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketStatusUpdatedEvent {
  export type InputTuple = [questionId: BytesLike, newStatus: BigNumberish];
  export type OutputTuple = [questionId: string, newStatus: bigint];
  export interface OutputObject {
    questionId: string;
    newStatus: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MarketRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): MarketRegistry;
  waitForDeployment(): Promise<this>;

  interface: MarketRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  adapter: TypedContractMethod<[], [string], "view">;

  allMarkets: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  createMarket: TypedContractMethod<
    [
      ipfsCid: string,
      outcomeCount: BigNumberish,
      resolutionTime: BigNumberish,
      settlementRail: BigNumberish
    ],
    [string],
    "nonpayable"
  >;

  getAllMarkets: TypedContractMethod<[], [string[]], "view">;

  getMarket: TypedContractMethod<
    [questionId: BytesLike],
    [MarketRegistry.MarketInfoStructOutput],
    "view"
  >;

  getMarketCount: TypedContractMethod<[], [bigint], "view">;

  getMarketsPage: TypedContractMethod<
    [offset: BigNumberish, limit: BigNumberish],
    [string[]],
    "view"
  >;

  marketSettlementRail: TypedContractMethod<
    [arg0: BytesLike],
    [bigint],
    "view"
  >;

  markets: TypedContractMethod<
    [arg0: BytesLike],
    [
      [bigint, bigint, bigint, boolean] & {
        outcomeCount: bigint;
        resolutionTime: bigint;
        status: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  syncStatus: TypedContractMethod<
    [questionId: BytesLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "adapter"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "allMarkets"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "createMarket"
  ): TypedContractMethod<
    [
      ipfsCid: string,
      outcomeCount: BigNumberish,
      resolutionTime: BigNumberish,
      settlementRail: BigNumberish
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAllMarkets"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getMarket"
  ): TypedContractMethod<
    [questionId: BytesLike],
    [MarketRegistry.MarketInfoStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMarketCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getMarketsPage"
  ): TypedContractMethod<
    [offset: BigNumberish, limit: BigNumberish],
    [string[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "marketSettlementRail"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "markets"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [bigint, bigint, bigint, boolean] & {
        outcomeCount: bigint;
        resolutionTime: bigint;
        status: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "syncStatus"
  ): TypedContractMethod<[questionId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "MarketCreated"
  ): TypedContractEvent<
    MarketCreatedEvent.InputTuple,
    MarketCreatedEvent.OutputTuple,
    MarketCreatedEvent.OutputObject
  >;
  getEvent(
    key: "MarketStatusUpdated"
  ): TypedContractEvent<
    MarketStatusUpdatedEvent.InputTuple,
    MarketStatusUpdatedEvent.OutputTuple,
    MarketStatusUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "MarketCreated(bytes32,string,uint256,uint256,address,uint8)": TypedContractEvent<
      MarketCreatedEvent.InputTuple,
      MarketCreatedEvent.OutputTuple,
      MarketCreatedEvent.OutputObject
    >;
    MarketCreated: TypedContractEvent<
      MarketCreatedEvent.InputTuple,
      MarketCreatedEvent.OutputTuple,
      MarketCreatedEvent.OutputObject
    >;

    "MarketStatusUpdated(bytes32,uint8)": TypedContractEvent<
      MarketStatusUpdatedEvent.InputTuple,
      MarketStatusUpdatedEvent.OutputTuple,
      MarketStatusUpdatedEvent.OutputObject
    >;
    MarketStatusUpdated: TypedContractEvent<
      MarketStatusUpdatedEvent.InputTuple,
      MarketStatusUpdatedEvent.OutputTuple,
      MarketStatusUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
