/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface PredictionMarketInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addLiquidity"
      | "buyTokensWithETH"
      | "getBuyPriceInEth"
      | "getPrediction"
      | "getSellPriceInEth"
      | "i_initialTokenValue"
      | "i_initialYesProbability"
      | "i_noToken"
      | "i_oracle"
      | "i_percentageLocked"
      | "i_yesToken"
      | "owner"
      | "redeemWinningTokens"
      | "removeLiquidity"
      | "renounceOwnership"
      | "report"
      | "resolveMarketAndWithdraw"
      | "s_ethCollateral"
      | "s_isReported"
      | "s_lpTradingRevenue"
      | "s_question"
      | "s_winningToken"
      | "sellTokensForEth"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "LiquidityAdded"
      | "LiquidityRemoved"
      | "MarketReported"
      | "MarketResolved"
      | "OwnershipTransferred"
      | "TokensPurchased"
      | "TokensSold"
      | "WinningTokensRedeemed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addLiquidity",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "buyTokensWithETH",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBuyPriceInEth",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPrediction",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSellPriceInEth",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "i_initialTokenValue",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "i_initialYesProbability",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "i_noToken", values?: undefined): string;
  encodeFunctionData(functionFragment: "i_oracle", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "i_percentageLocked",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "i_yesToken",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "redeemWinningTokens",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "removeLiquidity",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "report",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "resolveMarketAndWithdraw",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "s_ethCollateral",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "s_isReported",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "s_lpTradingRevenue",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "s_question",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "s_winningToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "sellTokensForEth",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "addLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "buyTokensWithETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBuyPriceInEth",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPrediction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSellPriceInEth",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "i_initialTokenValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "i_initialYesProbability",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "i_noToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "i_oracle", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "i_percentageLocked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "i_yesToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "redeemWinningTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "report", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "resolveMarketAndWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "s_ethCollateral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "s_isReported",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "s_lpTradingRevenue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "s_question", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "s_winningToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sellTokensForEth",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace LiquidityAddedEvent {
  export type InputTuple = [
    provider: AddressLike,
    ethAmount: BigNumberish,
    tokensAmount: BigNumberish
  ];
  export type OutputTuple = [
    provider: string,
    ethAmount: bigint,
    tokensAmount: bigint
  ];
  export interface OutputObject {
    provider: string;
    ethAmount: bigint;
    tokensAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidityRemovedEvent {
  export type InputTuple = [
    provider: AddressLike,
    ethAmount: BigNumberish,
    tokensAmount: BigNumberish
  ];
  export type OutputTuple = [
    provider: string,
    ethAmount: bigint,
    tokensAmount: bigint
  ];
  export interface OutputObject {
    provider: string;
    ethAmount: bigint;
    tokensAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketReportedEvent {
  export type InputTuple = [
    oracle: AddressLike,
    winningOutcome: BigNumberish,
    winningToken: AddressLike
  ];
  export type OutputTuple = [
    oracle: string,
    winningOutcome: bigint,
    winningToken: string
  ];
  export interface OutputObject {
    oracle: string;
    winningOutcome: bigint;
    winningToken: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketResolvedEvent {
  export type InputTuple = [
    resolver: AddressLike,
    totalEthToSend: BigNumberish
  ];
  export type OutputTuple = [resolver: string, totalEthToSend: bigint];
  export interface OutputObject {
    resolver: string;
    totalEthToSend: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokensPurchasedEvent {
  export type InputTuple = [
    buyer: AddressLike,
    outcome: BigNumberish,
    amount: BigNumberish,
    ethAmount: BigNumberish
  ];
  export type OutputTuple = [
    buyer: string,
    outcome: bigint,
    amount: bigint,
    ethAmount: bigint
  ];
  export interface OutputObject {
    buyer: string;
    outcome: bigint;
    amount: bigint;
    ethAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokensSoldEvent {
  export type InputTuple = [
    seller: AddressLike,
    outcome: BigNumberish,
    amount: BigNumberish,
    ethAmount: BigNumberish
  ];
  export type OutputTuple = [
    seller: string,
    outcome: bigint,
    amount: bigint,
    ethAmount: bigint
  ];
  export interface OutputObject {
    seller: string;
    outcome: bigint;
    amount: bigint;
    ethAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WinningTokensRedeemedEvent {
  export type InputTuple = [
    redeemer: AddressLike,
    amount: BigNumberish,
    ethAmount: BigNumberish
  ];
  export type OutputTuple = [
    redeemer: string,
    amount: bigint,
    ethAmount: bigint
  ];
  export interface OutputObject {
    redeemer: string;
    amount: bigint;
    ethAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PredictionMarket extends BaseContract {
  connect(runner?: ContractRunner | null): PredictionMarket;
  waitForDeployment(): Promise<this>;

  interface: PredictionMarketInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addLiquidity: TypedContractMethod<[], [void], "payable">;

  buyTokensWithETH: TypedContractMethod<
    [_outcome: BigNumberish, _amountTokenToBuy: BigNumberish],
    [void],
    "payable"
  >;

  getBuyPriceInEth: TypedContractMethod<
    [_outcome: BigNumberish, _tradingAmount: BigNumberish],
    [bigint],
    "view"
  >;

  getPrediction: TypedContractMethod<
    [],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        boolean,
        string,
        string,
        string,
        bigint,
        bigint,
        string,
        bigint,
        bigint
      ] & {
        question: string;
        outcome1: string;
        outcome2: string;
        oracle: string;
        initialTokenValue: bigint;
        yesTokenReserve: bigint;
        noTokenReserve: bigint;
        isReported: boolean;
        yesToken: string;
        noToken: string;
        winningToken: string;
        ethCollateral: bigint;
        lpTradingRevenue: bigint;
        predictionMarketOwner: string;
        initialProbability: bigint;
        percentageLocked: bigint;
      }
    ],
    "view"
  >;

  getSellPriceInEth: TypedContractMethod<
    [_outcome: BigNumberish, _tradingAmount: BigNumberish],
    [bigint],
    "view"
  >;

  i_initialTokenValue: TypedContractMethod<[], [bigint], "view">;

  i_initialYesProbability: TypedContractMethod<[], [bigint], "view">;

  i_noToken: TypedContractMethod<[], [string], "view">;

  i_oracle: TypedContractMethod<[], [string], "view">;

  i_percentageLocked: TypedContractMethod<[], [bigint], "view">;

  i_yesToken: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  redeemWinningTokens: TypedContractMethod<
    [_amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  removeLiquidity: TypedContractMethod<
    [_ethToWithdraw: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  report: TypedContractMethod<
    [_winningOutcome: BigNumberish],
    [void],
    "nonpayable"
  >;

  resolveMarketAndWithdraw: TypedContractMethod<[], [bigint], "nonpayable">;

  s_ethCollateral: TypedContractMethod<[], [bigint], "view">;

  s_isReported: TypedContractMethod<[], [boolean], "view">;

  s_lpTradingRevenue: TypedContractMethod<[], [bigint], "view">;

  s_question: TypedContractMethod<[], [string], "view">;

  s_winningToken: TypedContractMethod<[], [string], "view">;

  sellTokensForEth: TypedContractMethod<
    [_outcome: BigNumberish, _tradingAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addLiquidity"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "buyTokensWithETH"
  ): TypedContractMethod<
    [_outcome: BigNumberish, _amountTokenToBuy: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "getBuyPriceInEth"
  ): TypedContractMethod<
    [_outcome: BigNumberish, _tradingAmount: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPrediction"
  ): TypedContractMethod<
    [],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        boolean,
        string,
        string,
        string,
        bigint,
        bigint,
        string,
        bigint,
        bigint
      ] & {
        question: string;
        outcome1: string;
        outcome2: string;
        oracle: string;
        initialTokenValue: bigint;
        yesTokenReserve: bigint;
        noTokenReserve: bigint;
        isReported: boolean;
        yesToken: string;
        noToken: string;
        winningToken: string;
        ethCollateral: bigint;
        lpTradingRevenue: bigint;
        predictionMarketOwner: string;
        initialProbability: bigint;
        percentageLocked: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSellPriceInEth"
  ): TypedContractMethod<
    [_outcome: BigNumberish, _tradingAmount: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "i_initialTokenValue"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "i_initialYesProbability"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "i_noToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "i_oracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "i_percentageLocked"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "i_yesToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "redeemWinningTokens"
  ): TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeLiquidity"
  ): TypedContractMethod<[_ethToWithdraw: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "report"
  ): TypedContractMethod<[_winningOutcome: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resolveMarketAndWithdraw"
  ): TypedContractMethod<[], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "s_ethCollateral"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "s_isReported"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "s_lpTradingRevenue"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "s_question"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "s_winningToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "sellTokensForEth"
  ): TypedContractMethod<
    [_outcome: BigNumberish, _tradingAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "LiquidityAdded"
  ): TypedContractEvent<
    LiquidityAddedEvent.InputTuple,
    LiquidityAddedEvent.OutputTuple,
    LiquidityAddedEvent.OutputObject
  >;
  getEvent(
    key: "LiquidityRemoved"
  ): TypedContractEvent<
    LiquidityRemovedEvent.InputTuple,
    LiquidityRemovedEvent.OutputTuple,
    LiquidityRemovedEvent.OutputObject
  >;
  getEvent(
    key: "MarketReported"
  ): TypedContractEvent<
    MarketReportedEvent.InputTuple,
    MarketReportedEvent.OutputTuple,
    MarketReportedEvent.OutputObject
  >;
  getEvent(
    key: "MarketResolved"
  ): TypedContractEvent<
    MarketResolvedEvent.InputTuple,
    MarketResolvedEvent.OutputTuple,
    MarketResolvedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "TokensPurchased"
  ): TypedContractEvent<
    TokensPurchasedEvent.InputTuple,
    TokensPurchasedEvent.OutputTuple,
    TokensPurchasedEvent.OutputObject
  >;
  getEvent(
    key: "TokensSold"
  ): TypedContractEvent<
    TokensSoldEvent.InputTuple,
    TokensSoldEvent.OutputTuple,
    TokensSoldEvent.OutputObject
  >;
  getEvent(
    key: "WinningTokensRedeemed"
  ): TypedContractEvent<
    WinningTokensRedeemedEvent.InputTuple,
    WinningTokensRedeemedEvent.OutputTuple,
    WinningTokensRedeemedEvent.OutputObject
  >;

  filters: {
    "LiquidityAdded(address,uint256,uint256)": TypedContractEvent<
      LiquidityAddedEvent.InputTuple,
      LiquidityAddedEvent.OutputTuple,
      LiquidityAddedEvent.OutputObject
    >;
    LiquidityAdded: TypedContractEvent<
      LiquidityAddedEvent.InputTuple,
      LiquidityAddedEvent.OutputTuple,
      LiquidityAddedEvent.OutputObject
    >;

    "LiquidityRemoved(address,uint256,uint256)": TypedContractEvent<
      LiquidityRemovedEvent.InputTuple,
      LiquidityRemovedEvent.OutputTuple,
      LiquidityRemovedEvent.OutputObject
    >;
    LiquidityRemoved: TypedContractEvent<
      LiquidityRemovedEvent.InputTuple,
      LiquidityRemovedEvent.OutputTuple,
      LiquidityRemovedEvent.OutputObject
    >;

    "MarketReported(address,uint8,address)": TypedContractEvent<
      MarketReportedEvent.InputTuple,
      MarketReportedEvent.OutputTuple,
      MarketReportedEvent.OutputObject
    >;
    MarketReported: TypedContractEvent<
      MarketReportedEvent.InputTuple,
      MarketReportedEvent.OutputTuple,
      MarketReportedEvent.OutputObject
    >;

    "MarketResolved(address,uint256)": TypedContractEvent<
      MarketResolvedEvent.InputTuple,
      MarketResolvedEvent.OutputTuple,
      MarketResolvedEvent.OutputObject
    >;
    MarketResolved: TypedContractEvent<
      MarketResolvedEvent.InputTuple,
      MarketResolvedEvent.OutputTuple,
      MarketResolvedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "TokensPurchased(address,uint8,uint256,uint256)": TypedContractEvent<
      TokensPurchasedEvent.InputTuple,
      TokensPurchasedEvent.OutputTuple,
      TokensPurchasedEvent.OutputObject
    >;
    TokensPurchased: TypedContractEvent<
      TokensPurchasedEvent.InputTuple,
      TokensPurchasedEvent.OutputTuple,
      TokensPurchasedEvent.OutputObject
    >;

    "TokensSold(address,uint8,uint256,uint256)": TypedContractEvent<
      TokensSoldEvent.InputTuple,
      TokensSoldEvent.OutputTuple,
      TokensSoldEvent.OutputObject
    >;
    TokensSold: TypedContractEvent<
      TokensSoldEvent.InputTuple,
      TokensSoldEvent.OutputTuple,
      TokensSoldEvent.OutputObject
    >;

    "WinningTokensRedeemed(address,uint256,uint256)": TypedContractEvent<
      WinningTokensRedeemedEvent.InputTuple,
      WinningTokensRedeemedEvent.OutputTuple,
      WinningTokensRedeemedEvent.OutputObject
    >;
    WinningTokensRedeemed: TypedContractEvent<
      WinningTokensRedeemedEvent.InputTuple,
      WinningTokensRedeemedEvent.OutputTuple,
      WinningTokensRedeemedEvent.OutputObject
    >;
  };
}
