/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace PredictionMarketAMM {
  export type LpPnLSummaryStruct = {
    totalDeposited: BigNumberish;
    totalWithdrawn: BigNumberish;
    tradingRevenue: BigNumberish;
    poolInventory: BigNumberish;
    walletInventory: BigNumberish;
    nav: BigNumberish;
    netPnl: BigNumberish;
  };

  export type LpPnLSummaryStructOutput = [
    totalDeposited: bigint,
    totalWithdrawn: bigint,
    tradingRevenue: bigint,
    poolInventory: bigint,
    walletInventory: bigint,
    nav: bigint,
    netPnl: bigint
  ] & {
    totalDeposited: bigint;
    totalWithdrawn: bigint;
    tradingRevenue: bigint;
    poolInventory: bigint;
    walletInventory: bigint;
    nav: bigint;
    netPnl: bigint;
  };

  export type PoolStruct = {
    yesTokenId: BigNumberish;
    noTokenId: BigNumberish;
    yesReserve: BigNumberish;
    noReserve: BigNumberish;
    usdcCollateral: BigNumberish;
    lpTradingRevenue: BigNumberish;
    lpTotalDeposited: BigNumberish;
    lpTotalWithdrawn: BigNumberish;
    initialYesProbability: BigNumberish;
    percentageLocked: BigNumberish;
    lpOwner: AddressLike;
    resolved: boolean;
    exists: boolean;
  };

  export type PoolStructOutput = [
    yesTokenId: bigint,
    noTokenId: bigint,
    yesReserve: bigint,
    noReserve: bigint,
    usdcCollateral: bigint,
    lpTradingRevenue: bigint,
    lpTotalDeposited: bigint,
    lpTotalWithdrawn: bigint,
    initialYesProbability: bigint,
    percentageLocked: bigint,
    lpOwner: string,
    resolved: boolean,
    exists: boolean
  ] & {
    yesTokenId: bigint;
    noTokenId: bigint;
    yesReserve: bigint;
    noReserve: bigint;
    usdcCollateral: bigint;
    lpTradingRevenue: bigint;
    lpTotalDeposited: bigint;
    lpTotalWithdrawn: bigint;
    initialYesProbability: bigint;
    percentageLocked: bigint;
    lpOwner: string;
    resolved: boolean;
    exists: boolean;
  };
}

export interface PredictionMarketAMMInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addLiquidity"
      | "allPools"
      | "buyTokens"
      | "collateral"
      | "createPool"
      | "ctf"
      | "getAllPools"
      | "getBuyPrice"
      | "getLpNav"
      | "getLpPnLSummary"
      | "getLpWalletInventoryValue"
      | "getPool"
      | "getPoolInventoryValue"
      | "getSellPrice"
      | "getYesProbability"
      | "markResolved"
      | "onERC1155BatchReceived"
      | "onERC1155Received"
      | "owner"
      | "pools"
      | "removeLiquidity"
      | "renounceOwnership"
      | "sellTokens"
      | "supportsInterface"
      | "transferOwnership"
      | "withdrawAfterResolution"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "LiquidityAdded"
      | "LiquidityRemoved"
      | "OwnershipTransferred"
      | "PoolCreated"
      | "PoolResolved"
      | "TokensBought"
      | "TokensSold"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addLiquidity",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "allPools",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "buyTokens",
    values: [BytesLike, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "collateral",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createPool",
    values: [
      BytesLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(functionFragment: "ctf", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getAllPools",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBuyPrice",
    values: [BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getLpNav", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getLpPnLSummary",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getLpWalletInventoryValue",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "getPool", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getPoolInventoryValue",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSellPrice",
    values: [BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getYesProbability",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "markResolved",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "onERC1155BatchReceived",
    values: [
      AddressLike,
      AddressLike,
      BigNumberish[],
      BigNumberish[],
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "onERC1155Received",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pools", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "removeLiquidity",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "sellTokens",
    values: [BytesLike, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawAfterResolution",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "addLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "allPools", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "buyTokens", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "collateral", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "createPool", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ctf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAllPools",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBuyPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getLpNav", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getLpPnLSummary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLpWalletInventoryValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPoolInventoryValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSellPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getYesProbability",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "markResolved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onERC1155BatchReceived",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onERC1155Received",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pools", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sellTokens", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawAfterResolution",
    data: BytesLike
  ): Result;
}

export namespace LiquidityAddedEvent {
  export type InputTuple = [
    conditionId: BytesLike,
    provider: AddressLike,
    usdcAmount: BigNumberish,
    tokenAmount: BigNumberish
  ];
  export type OutputTuple = [
    conditionId: string,
    provider: string,
    usdcAmount: bigint,
    tokenAmount: bigint
  ];
  export interface OutputObject {
    conditionId: string;
    provider: string;
    usdcAmount: bigint;
    tokenAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidityRemovedEvent {
  export type InputTuple = [
    conditionId: BytesLike,
    provider: AddressLike,
    usdcAmount: BigNumberish,
    tokenAmount: BigNumberish
  ];
  export type OutputTuple = [
    conditionId: string,
    provider: string,
    usdcAmount: bigint,
    tokenAmount: bigint
  ];
  export interface OutputObject {
    conditionId: string;
    provider: string;
    usdcAmount: bigint;
    tokenAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PoolCreatedEvent {
  export type InputTuple = [
    conditionId: BytesLike,
    yesTokenId: BigNumberish,
    noTokenId: BigNumberish,
    usdcCollateral: BigNumberish
  ];
  export type OutputTuple = [
    conditionId: string,
    yesTokenId: bigint,
    noTokenId: bigint,
    usdcCollateral: bigint
  ];
  export interface OutputObject {
    conditionId: string;
    yesTokenId: bigint;
    noTokenId: bigint;
    usdcCollateral: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PoolResolvedEvent {
  export type InputTuple = [conditionId: BytesLike];
  export type OutputTuple = [conditionId: string];
  export interface OutputObject {
    conditionId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokensBoughtEvent {
  export type InputTuple = [
    conditionId: BytesLike,
    buyer: AddressLike,
    outcome: BigNumberish,
    tokenAmount: BigNumberish,
    usdcPaid: BigNumberish
  ];
  export type OutputTuple = [
    conditionId: string,
    buyer: string,
    outcome: bigint,
    tokenAmount: bigint,
    usdcPaid: bigint
  ];
  export interface OutputObject {
    conditionId: string;
    buyer: string;
    outcome: bigint;
    tokenAmount: bigint;
    usdcPaid: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokensSoldEvent {
  export type InputTuple = [
    conditionId: BytesLike,
    seller: AddressLike,
    outcome: BigNumberish,
    tokenAmount: BigNumberish,
    usdcReceived: BigNumberish
  ];
  export type OutputTuple = [
    conditionId: string,
    seller: string,
    outcome: bigint,
    tokenAmount: bigint,
    usdcReceived: bigint
  ];
  export interface OutputObject {
    conditionId: string;
    seller: string;
    outcome: bigint;
    tokenAmount: bigint;
    usdcReceived: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PredictionMarketAMM extends BaseContract {
  connect(runner?: ContractRunner | null): PredictionMarketAMM;
  waitForDeployment(): Promise<this>;

  interface: PredictionMarketAMMInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addLiquidity: TypedContractMethod<
    [conditionId: BytesLike, usdcAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  allPools: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  buyTokens: TypedContractMethod<
    [
      conditionId: BytesLike,
      outcome: BigNumberish,
      tokenAmount: BigNumberish,
      maxUsdcIn: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  collateral: TypedContractMethod<[], [string], "view">;

  createPool: TypedContractMethod<
    [
      conditionId: BytesLike,
      yesTokenId: BigNumberish,
      noTokenId: BigNumberish,
      usdcAmount: BigNumberish,
      initialYesProbability: BigNumberish,
      percentageToLock: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  ctf: TypedContractMethod<[], [string], "view">;

  getAllPools: TypedContractMethod<[], [string[]], "view">;

  getBuyPrice: TypedContractMethod<
    [conditionId: BytesLike, outcome: BigNumberish, tokenAmount: BigNumberish],
    [bigint],
    "view"
  >;

  getLpNav: TypedContractMethod<[conditionId: BytesLike], [bigint], "view">;

  getLpPnLSummary: TypedContractMethod<
    [conditionId: BytesLike],
    [PredictionMarketAMM.LpPnLSummaryStructOutput],
    "view"
  >;

  getLpWalletInventoryValue: TypedContractMethod<
    [conditionId: BytesLike, lp: AddressLike],
    [bigint],
    "view"
  >;

  getPool: TypedContractMethod<
    [conditionId: BytesLike],
    [PredictionMarketAMM.PoolStructOutput],
    "view"
  >;

  getPoolInventoryValue: TypedContractMethod<
    [conditionId: BytesLike],
    [bigint],
    "view"
  >;

  getSellPrice: TypedContractMethod<
    [conditionId: BytesLike, outcome: BigNumberish, tokenAmount: BigNumberish],
    [bigint],
    "view"
  >;

  getYesProbability: TypedContractMethod<
    [conditionId: BytesLike],
    [bigint],
    "view"
  >;

  markResolved: TypedContractMethod<
    [conditionId: BytesLike],
    [void],
    "nonpayable"
  >;

  onERC1155BatchReceived: TypedContractMethod<
    [
      arg0: AddressLike,
      arg1: AddressLike,
      arg2: BigNumberish[],
      arg3: BigNumberish[],
      arg4: BytesLike
    ],
    [string],
    "view"
  >;

  onERC1155Received: TypedContractMethod<
    [
      arg0: AddressLike,
      arg1: AddressLike,
      arg2: BigNumberish,
      arg3: BigNumberish,
      arg4: BytesLike
    ],
    [string],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pools: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        boolean,
        boolean
      ] & {
        yesTokenId: bigint;
        noTokenId: bigint;
        yesReserve: bigint;
        noReserve: bigint;
        usdcCollateral: bigint;
        lpTradingRevenue: bigint;
        lpTotalDeposited: bigint;
        lpTotalWithdrawn: bigint;
        initialYesProbability: bigint;
        percentageLocked: bigint;
        lpOwner: string;
        resolved: boolean;
        exists: boolean;
      }
    ],
    "view"
  >;

  removeLiquidity: TypedContractMethod<
    [conditionId: BytesLike, usdcAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  sellTokens: TypedContractMethod<
    [
      conditionId: BytesLike,
      outcome: BigNumberish,
      tokenAmount: BigNumberish,
      minUsdcOut: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  withdrawAfterResolution: TypedContractMethod<
    [conditionId: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addLiquidity"
  ): TypedContractMethod<
    [conditionId: BytesLike, usdcAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "allPools"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "buyTokens"
  ): TypedContractMethod<
    [
      conditionId: BytesLike,
      outcome: BigNumberish,
      tokenAmount: BigNumberish,
      maxUsdcIn: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "collateral"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "createPool"
  ): TypedContractMethod<
    [
      conditionId: BytesLike,
      yesTokenId: BigNumberish,
      noTokenId: BigNumberish,
      usdcAmount: BigNumberish,
      initialYesProbability: BigNumberish,
      percentageToLock: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "ctf"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getAllPools"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getBuyPrice"
  ): TypedContractMethod<
    [conditionId: BytesLike, outcome: BigNumberish, tokenAmount: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getLpNav"
  ): TypedContractMethod<[conditionId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getLpPnLSummary"
  ): TypedContractMethod<
    [conditionId: BytesLike],
    [PredictionMarketAMM.LpPnLSummaryStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getLpWalletInventoryValue"
  ): TypedContractMethod<
    [conditionId: BytesLike, lp: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPool"
  ): TypedContractMethod<
    [conditionId: BytesLike],
    [PredictionMarketAMM.PoolStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPoolInventoryValue"
  ): TypedContractMethod<[conditionId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getSellPrice"
  ): TypedContractMethod<
    [conditionId: BytesLike, outcome: BigNumberish, tokenAmount: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getYesProbability"
  ): TypedContractMethod<[conditionId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "markResolved"
  ): TypedContractMethod<[conditionId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "onERC1155BatchReceived"
  ): TypedContractMethod<
    [
      arg0: AddressLike,
      arg1: AddressLike,
      arg2: BigNumberish[],
      arg3: BigNumberish[],
      arg4: BytesLike
    ],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "onERC1155Received"
  ): TypedContractMethod<
    [
      arg0: AddressLike,
      arg1: AddressLike,
      arg2: BigNumberish,
      arg3: BigNumberish,
      arg4: BytesLike
    ],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pools"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        boolean,
        boolean
      ] & {
        yesTokenId: bigint;
        noTokenId: bigint;
        yesReserve: bigint;
        noReserve: bigint;
        usdcCollateral: bigint;
        lpTradingRevenue: bigint;
        lpTotalDeposited: bigint;
        lpTotalWithdrawn: bigint;
        initialYesProbability: bigint;
        percentageLocked: bigint;
        lpOwner: string;
        resolved: boolean;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "removeLiquidity"
  ): TypedContractMethod<
    [conditionId: BytesLike, usdcAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "sellTokens"
  ): TypedContractMethod<
    [
      conditionId: BytesLike,
      outcome: BigNumberish,
      tokenAmount: BigNumberish,
      minUsdcOut: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawAfterResolution"
  ): TypedContractMethod<[conditionId: BytesLike], [void], "nonpayable">;

  getEvent(
    key: "LiquidityAdded"
  ): TypedContractEvent<
    LiquidityAddedEvent.InputTuple,
    LiquidityAddedEvent.OutputTuple,
    LiquidityAddedEvent.OutputObject
  >;
  getEvent(
    key: "LiquidityRemoved"
  ): TypedContractEvent<
    LiquidityRemovedEvent.InputTuple,
    LiquidityRemovedEvent.OutputTuple,
    LiquidityRemovedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PoolCreated"
  ): TypedContractEvent<
    PoolCreatedEvent.InputTuple,
    PoolCreatedEvent.OutputTuple,
    PoolCreatedEvent.OutputObject
  >;
  getEvent(
    key: "PoolResolved"
  ): TypedContractEvent<
    PoolResolvedEvent.InputTuple,
    PoolResolvedEvent.OutputTuple,
    PoolResolvedEvent.OutputObject
  >;
  getEvent(
    key: "TokensBought"
  ): TypedContractEvent<
    TokensBoughtEvent.InputTuple,
    TokensBoughtEvent.OutputTuple,
    TokensBoughtEvent.OutputObject
  >;
  getEvent(
    key: "TokensSold"
  ): TypedContractEvent<
    TokensSoldEvent.InputTuple,
    TokensSoldEvent.OutputTuple,
    TokensSoldEvent.OutputObject
  >;

  filters: {
    "LiquidityAdded(bytes32,address,uint256,uint256)": TypedContractEvent<
      LiquidityAddedEvent.InputTuple,
      LiquidityAddedEvent.OutputTuple,
      LiquidityAddedEvent.OutputObject
    >;
    LiquidityAdded: TypedContractEvent<
      LiquidityAddedEvent.InputTuple,
      LiquidityAddedEvent.OutputTuple,
      LiquidityAddedEvent.OutputObject
    >;

    "LiquidityRemoved(bytes32,address,uint256,uint256)": TypedContractEvent<
      LiquidityRemovedEvent.InputTuple,
      LiquidityRemovedEvent.OutputTuple,
      LiquidityRemovedEvent.OutputObject
    >;
    LiquidityRemoved: TypedContractEvent<
      LiquidityRemovedEvent.InputTuple,
      LiquidityRemovedEvent.OutputTuple,
      LiquidityRemovedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PoolCreated(bytes32,uint256,uint256,uint256)": TypedContractEvent<
      PoolCreatedEvent.InputTuple,
      PoolCreatedEvent.OutputTuple,
      PoolCreatedEvent.OutputObject
    >;
    PoolCreated: TypedContractEvent<
      PoolCreatedEvent.InputTuple,
      PoolCreatedEvent.OutputTuple,
      PoolCreatedEvent.OutputObject
    >;

    "PoolResolved(bytes32)": TypedContractEvent<
      PoolResolvedEvent.InputTuple,
      PoolResolvedEvent.OutputTuple,
      PoolResolvedEvent.OutputObject
    >;
    PoolResolved: TypedContractEvent<
      PoolResolvedEvent.InputTuple,
      PoolResolvedEvent.OutputTuple,
      PoolResolvedEvent.OutputObject
    >;

    "TokensBought(bytes32,address,uint256,uint256,uint256)": TypedContractEvent<
      TokensBoughtEvent.InputTuple,
      TokensBoughtEvent.OutputTuple,
      TokensBoughtEvent.OutputObject
    >;
    TokensBought: TypedContractEvent<
      TokensBoughtEvent.InputTuple,
      TokensBoughtEvent.OutputTuple,
      TokensBoughtEvent.OutputObject
    >;

    "TokensSold(bytes32,address,uint256,uint256,uint256)": TypedContractEvent<
      TokensSoldEvent.InputTuple,
      TokensSoldEvent.OutputTuple,
      TokensSoldEvent.OutputObject
    >;
    TokensSold: TypedContractEvent<
      TokensSoldEvent.InputTuple,
      TokensSoldEvent.OutputTuple,
      TokensSoldEvent.OutputObject
    >;
  };
}
